inherit_from:
  - https://gist.githubusercontent.com/eki/b7081085e7a447bb6c1e354bde0631d8/raw

Naming/PredicateName:
  AllowedMethods:
    - has_moves
    - has_moves?
    - has_score?
    - has_special_moves
    - has_special_moves?
    - has_neighbor?
