require 'rake'
require 'rake/testtask'

begin
  require 'rubygems'
  require 'rake/gempackagetask'
rescue Exception
  nil
end

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/test*.rb']
end


if defined?( Gem ) && ENV['PKG_VERSION']
  PKG_VERSION = ENV['PKG_VERSION']
  PKG_FILES = FileList[
    'lib/**/*.rb',
    'bin/**/*',
    'test/**/*.rb',
    '[A-Z]*']

  spec = Gem::Specification.new do |s|
    s.name = 'vying'
    s.version = ENV['PKG_VERSION']
    s.summary = 'Vying Game Library'
    s.description = 'Vying is a game library.'
    s.files = PKG_FILES.to_a
    s.executables = ['branch', 'bench']
    s.author = 'Eric K Idema'
    s.email = 'eki@vying.org'
  end

  package_task = Rake::GemPackageTask.new( spec ) do |pkg|
    pkg.need_tar_gz = true
  end
end

