require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/clean'
require 'fileutils'
include FileUtils

begin
  require 'rubygems'
  require 'rake/gempackagetask'
rescue Exception
  nil
end

CLEAN.include( 'ext/**/*.o', 'ext/**/*.so' )
CLOBBER.include( 'pkg' )

Rake::TestTask.new do |t|
  t.libs << "test" << "ext"
  t.test_files = FileList['test/**/*_test.rb']
end

Rake::RDocTask.new do |rd|
  rd.main = "README"
  rd.rdoc_dir = "doc/api"
  rd.rdoc_files.include( "README", "doc/*.txt", "lib/**/*.rb", 
                         "ext/**/*.h", "ext/**/*.c" )
end

task :compile do 
  sh %{cd ext/vying/board && ruby ./extconf.rb && make}
end

task :default => [:clean, :compile, :test]

wd = Dir.pwd
wd =~ /\/v([\d\.]*)$/
pkg_version = $1

if defined?( Gem ) && pkg_version
  PKG_FILES = FileList[
    'lib/**/*',
    'bin/bench',
    'bin/branch',
    'test/**/*',
    'ext/**/*',
    'Rakefile']

  spec = Gem::Specification.new do |s|
    s.name = 'vying'
    s.version = pkg_version
    s.summary = 'Vying Game Library'
    s.description = 'Vying is a game library.'
    s.files = PKG_FILES.to_a
    s.extensions = "ext/vying/board/extconf.rb"
    s.executables = ['branch', 'bench']
    s.require_paths << "ext"
    s.author = 'Eric K Idema'
    s.email = 'eki@vying.org'
  end

  package_task = Rake::GemPackageTask.new( spec ) do |pkg|
    pkg.need_tar_gz = true
  end
end

