require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/clean'
require 'fileutils'
include FileUtils

###
### cleanup tasks
###

CLEAN.include( 'ext/**/*.o', 'ext/**/*.so' )
CLOBBER.include( 'pkg', 'doc/api', 'doc/coverage' )

###
### test task
###

Rake::TestTask.new do |t|
  t.libs << "test" << "ext"
  t.test_files = FileList['test/**/*_test.rb']
end

###
### rdoc task
###

Rake::RDocTask.new do |rd|
  rd.main = "README"
  rd.rdoc_dir = "doc/api"
  rd.rdoc_files.include( "README", "LICENSE", "COPYING", 
                         "doc/*.txt", "lib/**/*.rb", 
                         "ext/**/*.h", "ext/**/*.c" )
end

###
### task to compile the extension
###

desc "compile the C extension part of the vying library"
task :compile do 
  sh %{cd ext/vying/board && ruby ./extconf.rb && make}
end

###
### the default task
###

task :default => [:clean, :compile, :test]

###
###  RubyGems related tasks follow:
###

wd = Dir.pwd
wd =~ /\/v([\d\.]*)$/
pkg_version = $1

desc "Appends the tagged version to lib/vying.rb"
task :version do
  sh %{echo 'module Vying; VERSION = "#{pkg_version}"; end' >> lib/vying.rb}
end

begin
  require 'rubygems'
  require 'rake/gempackagetask'
rescue Exception
  nil
end

if defined?( Gem ) && pkg_version
  task :gem => [:clean, :compile, :test, :version]

  PKG_FILES = FileList[
    'lib/**/*',
    'bin/vying',
    'test/**/*',
    'ext/**/*',
    'Rakefile',
    'README',
    'LICENSE',
    'COPYING']

  spec = Gem::Specification.new do |s|
    s.name = 'vying'
    s.version = pkg_version
    s.summary = 'Vying Game Library'
    s.description = 'Vying is a game library.'
    s.files = PKG_FILES.to_a
    s.extensions = "ext/vying/board/extconf.rb"
    s.executables = ['vying']
    s.add_dependency "random", ">= 0.2.1"
    s.add_dependency "sqlite-ruby", ">= 2.2.3"
    s.require_paths << "ext"
    s.author = 'Eric K Idema'
    s.email = 'eki@vying.org'
  end

  package_task = Rake::GemPackageTask.new( spec ) do |pkg|
    pkg.need_tar_gz = true
  end
end

###
### Rcov related tasks follow
###

begin
  require 'rcov/rcovtask'
rescue Exception
  nil
end

if defined?( Rcov )
  task :rcov => [:compile]

  Rcov::RcovTask.new do |t|
    t.libs << "test" << "ext"
    t.test_files = FileList['test/**/*_test.rb']
    t.output_dir = "doc/coverage"
  end
end

